name = "magloop_field"
description = "magloop_field"
packages = ["markdown", "scipy", "numpy", "matplotlib"]

[files]
"./index_readme.py" = ""
"./index.py" = ""
"./README.md" = ""
"./src/magloop_field/calculations.py" = "./magloop_field/calculations.py"
"./src/magloop_field/diagram.py" = "./magloop_field/diagram.py"
