S1P_EXTENSION = ".s1p"
SMITH_SUFFIX = "_SMITH"
SWR_SUFFIX = "_SWR"
DELAY_SUFFIX = "_DELAY"
VALUES_SUFFIX = "_VALUES"
SKIP_VALUES_FILENAME_SUFFIX = "_SKIP_values.py"
SVG_EXTENSION = ".svg"
MEASUREMENTS_SUBDIR = "s1p_measurements"
DIRECTORY_S1P_RESULTS = "s1p_results"
CAP_VALUES_TAGS = ("CAP_NIX", "CAP_OFF", "CAP_100P", "CAP_560P")

C_100P_F = 100e-12
C_560P_F = 579e-12
